#!/usr/bin/env bash

set -xeuo pipefail

export SCRIPT_DIR="$(dirname "$0")"

# Directory to store the coverage reports in
ONLY_TEST_PACKAGES=${ONLY_TEST_PACKAGES:-}

CHECK_DIRECTORY=${CHECK_DIRECTORY:-.}

CARGO_CHANNEL=${CARGO_CHANNEL:-}

ALL_TARGETS_FLAG=""
if [[ "$ALL_TARGETS" == "true" ]]; then
    ALL_TARGETS_FLAG="--all-targets"
fi

OLD_PWD="$PWD"

finish() {
    cd "$OLD_PWD"
}

trap finish EXIT

cd "$CHECK_DIRECTORY"

printf "\n\n--== Directory $CHECK_DIRECTORY ==--\n\n"
ls

printf "\n\n--== Build Environment ==--\n\n"
rustc \
    --version
cargo \
    --version

# Run check
printf "\n\n--== Run Build ==--\n\n"
cargo ${CARGO_CHANNEL:++$CARGO_CHANNEL} \
    check"$COMMAND_SUFFIX" \
    ${ALL_TARGETS_FLAG:+$ALL_TARGETS_FLAG}

# Run cargo fmt
printf "\n\n--== Check Code Formatting ==--\n\n"
cargo fmt --all \
    -- \
        --check

# Run cargo clippy
printf "\n\n--== Run Linter ==--\n\n"
cargo ${CARGO_CHANNEL:++$CARGO_CHANNEL} \
    clippy"$COMMAND_SUFFIX" \
    ${ALL_TARGETS_FLAG:+$ALL_TARGETS_FLAG} \
    -- \
        --deny "warnings"


# Run cargo doc
printf "\n\n--== Check Doc ==--\n\n"

RUSTDOCFLAGS="-D warnings" \
cargo ${CARGO_CHANNEL:++$CARGO_CHANNEL} \
    doc"$COMMAND_SUFFIX" \
    --no-deps \
    --document-private-items

# Run cargo nextest
PACKAGE_ARGS=()
if [ -n "$ONLY_TEST_PACKAGES" ]; then
    for PACKAGE in $ONLY_TEST_PACKAGES; do
        PACKAGE_ARGS+=('-p' "$PACKAGE")
    done
fi

printf "\n\n--== Run Unit Tests ==--\n\n"
RUSTFLAGS="-D warnings" \
    cargo ${CARGO_CHANNEL:++$CARGO_CHANNEL} nextest"$COMMAND_SUFFIX" \
    --no-fail-fast \
    "${PACKAGE_ARGS[@]}"
