#!/usr/bin/env bash

set -euo pipefail

# Whether to check the code format or not
RUN_CARGO_FMT=${RUN_CARGO_FMT:-true}

# Globally enable or disable cargo clippy execution
RUN_CARGO_CLIPPY=${RUN_CARGO_CLIPPY:-true}

# Globally enable or disable cargo doc execution
RUN_CARGO_DOC=${RUN_CARGO_DOC:-true}

# Globally enable or disable cargo test execution
RUN_CARGO_TEST=${RUN_CARGO_TEST:-true}

# Globally enable or disable cargo test execution with code coverage
RUN_CARGO_TEST_WITH_COVERAGE=${RUN_CARGO_TEST_WITH_COVERAGE:-true}

# Globally include doc tests in the coverage results
INCLUDE_DOC_TESTS=${INCLUDE_DOC_TESTS:-false}

PACKAGES=${PACKAGES:?"PACKAGES is unset!"}
PROJECT_ROOT="${PROJECT_ROOT:?"PROJECT_ROOT is unset!"}"

OLD_PWD="$PWD"

finish() {
    cd "$OLD_PWD"
}

trap finish EXIT

cd "$PROJECT_ROOT"

printf "\n\n--== Build Environment ==--\n\n"
rustc \
    --version
cargo \
    --version

parsePackageTuple() {
    IFS=',' \
      read -r \
      PACKAGE \
      DO_RUN_CARGO_CLIPPY \
      DO_RUN_CARGO_DOC \
      DO_RUN_CARGO_TEST \
      EXPECTED_COVERAGE \
      <<< "$1"

    EXPECTED_COVERAGE=${EXPECTED_COVERAGE:-""}
}

# Run cargo fmt
if [ "$RUN_CARGO_FMT" = "true" ]; then
    printf "\n\n--== Check Code Style ==--\n\n"
    cargo fmt \
        --all \
        -- \
            --check
fi

# Run cargo clippy
if [ "$RUN_CARGO_CLIPPY" = "true" ]; then
    for ARGS in $PACKAGES; do
        parsePackageTuple "$ARGS"

        if [ "$DO_RUN_CARGO_CLIPPY" = "false" ]; then
            continue
        fi

        printf "\n\n--== Run Linter for %s ==--\n\n" "$PACKAGE"

        cargo clippy \
            -p "$PACKAGE" \
            --all-targets \
            $CARGO_EXTRA_ARGS \
            -- \
                --deny "warnings"
    done
fi

# Run cargo doc
if [ "$RUN_CARGO_DOC" = "true" ]; then
    for ARGS in $PACKAGES; do
        parsePackageTuple "$ARGS"

        if [ "$DO_RUN_CARGO_DOC" = "false" ]; then
            continue
        fi

        printf "\n\n--== Check Doc for %s ==--\n\n" "$PACKAGE"

        RUSTDOCFLAGS="-D warnings" \
        cargo doc \
            -p "$PACKAGE" \
            --no-deps \
            $CARGO_EXTRA_ARGS \
            --document-private-items
    done
fi

# Run cargo test
for ARGS in $PACKAGES; do
    parsePackageTuple "$ARGS"

    if [ "$RUN_CARGO_TEST" = "false" ]; then
        DO_RUN_CARGO_TEST="false"
    fi

    if [ "$RUN_CARGO_TEST_WITH_COVERAGE" = "false" ]; then
        EXPECTED_COVERAGE=""
    fi

    if [ -n "$EXPECTED_COVERAGE" ]; then
        printf "\n\n--== Unit Tests (With Coverage) for %s ==--\n\n" "$PACKAGE"

        # Execute the tests
        if [ "$INCLUDE_DOC_TESTS" = "true" ]; then
            printf "\n\n--== Doc Tests (With Coverage) for %s ==--\n\n" "$PACKAGE"

            # implement later, when there's a need. (it should be fairly straight-forward)
            # https://nexte.st/docs/integrations/test-coverage/
        else
            cargo llvm-cov \
              nextest \
              -p "$PACKAGE" \
              --json \
              --output-path coverage/coverage.json

            cargo llvm-cov \
              report \
              -p "$PACKAGE" \
              --html \
              --output-dir coverage
        fi

        COVERAGE_PERCENTAGE=$(jq '.data[0].totals.regions.percent' < coverage/coverage.json)

        # Check test coverage
        if [ $(echo "$COVERAGE_PERCENTAGE < $EXPECTED_COVERAGE" | bc -l) = 1 ]; then
            echo ""
            echo "Test coverage for '$PACKAGE' is not fulfilled"
            echo "    actual coverage:   $COVERAGE_PERCENTAGE %"
            echo "    expected coverage: $EXPECTED_COVERAGE %"
            exit 1
        fi
    elif [ "$DO_RUN_CARGO_TEST" = "true" ]; then
        printf "\n\n--== Unit Tests for %s ==--\n\n" "$PACKAGE"

        RUSTFLAGS="-D warnings" \
        cargo nextest run \
            $CARGO_EXTRA_ARGS \
            -p "$PACKAGE"

    fi
done
